### ISSUE TITLE
Buld against MDAL

### ISSUE THREAD

**Issue by mdsumner** [mdsumner/rmdal0#1]
@mpadge if you have a chance at making this minimal example work? I've attempted in to build against https://github.com/lutraconsulting/MDAL which has in-built data sets and a simpl-ish looking version and info summary in the API. It's built with cmake which I have no clue about, and might be why I couldn't bash through it.

There's no great priority on this from my perspective, just a neat crossover if we can get it in R.

**Comment by mdsumner** [comment]
All good

**Comment by mpadge** [comment]
Wow, that looks awesome!

**Comment by mdsumner** [comment]
Actually I'm a bit hit and miss so far, can't get MDAL_driverCount() or MDAL_Version() to work, maybe some subtlety ?? Also confused about need for mdal_config hence currently hard coded as I tested things

**Comment by mpadge** [comment]
Did you try just wrapping the [C++ `src` itself](https://github.com/lutraconsulting/MDAL/tree/master/mdal), and calling the functions directly from there? That would surely be the easiest, and possible coz of MIT license

**Comment by mdsumner** [comment]
I haven't, and not sure how to go about that - you copy all the contents of that folder into src/ yeah?

**Comment by mpadge** [comment]
It's structured a bit differently, so you'd have to move some of them around a bit, and change the internal header links. I'll give it go next week, if you can wait that long ...

**Comment by mdsumner** [comment]
Yeah no worries!
